services:
  - type: pserv
    name: mongodb
    env: docker
    autoDeploy: false
    disk:
      name: data
      mountPath: /data/db
      sizeGB: 10
    dockerCommand: "/bin/sh -c '/usr/sbin/sshd -D & mongod --config /etc/mongod.conf'"