services:
  - type: pserv
    name: mongodb
    env: docker
    autoDeploy: false
    disk:
      name: data
      mountPath: /data/db
      sizeGB: 10
    envVars:
      - key: GLIBC_TUNABLES
        value: "glibc.pthread.rseq=0"
